<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from /Users/sunil/svn/sunil/customer/skvare/sunil/drupal-7.72_testing/sites/default/files/civicrm/ext/com.skvare.geocodestats/xml/schema/CRM/Geocodestats/Geocodestats.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c9fbac680b9584ecbd08ae4064262f83)
 */
use CRM_Geocodestats_ExtensionUtil as E;

/**
 * Database access object for the Geocodestats entity.
 */
class CRM_Geocodestats_DAO_Geocodestats extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_geocodestats';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Geocodestats ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Contact
   *
   * @var int
   */
  public $address_id;

  /**
   * @var string
   */
  public $provider;

  /**
   * @var string
   */
  public $status;

  /**
   * When was the Geo code call was initiated.
   *
   * @var timestamp
   */
  public $created_date;

  /**
   * Latitude
   *
   * @var float
   */
  public $geo_code_1;

  /**
   * Longitude
   *
   * @var float
   */
  public $geo_code_2;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_geocodestats';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Geocodestatses') : E::ts('Geocodestats');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'address_id', 'civicrm_address', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique Geocodestats ID'),
          'required' => TRUE,
          'where' => 'civicrm_geocodestats.id',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'address_id' => [
          'name' => 'address_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact'),
          'where' => 'civicrm_geocodestats.address_id',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_Address',
          'add' => NULL,
        ],
        'provider' => [
          'name' => 'provider',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Provider'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_geocodestats.provider',
          'default' => 'NULL',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'add' => NULL,
        ],
        'status' => [
          'name' => 'status',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Status'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_geocodestats.status',
          'default' => 'NULL',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Geocodestats_BAO_Geocodestats::status',
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => E::ts('Created Date'),
          'description' => E::ts('When was the Geo code call was initiated.'),
          'required' => FALSE,
          'where' => 'civicrm_geocodestats.created_date',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'add' => '5.27',
        ],
        'geocodestats_geo_code_1' => [
          'name' => 'geo_code_1',
          'type' => CRM_Utils_Type::T_FLOAT,
          'title' => E::ts('Latitude'),
          'description' => E::ts('Latitude'),
          'where' => 'civicrm_geocodestats.geo_code_1',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.27',
        ],
        'geocodestats_geo_code_2' => [
          'name' => 'geo_code_2',
          'type' => CRM_Utils_Type::T_FLOAT,
          'title' => E::ts('Longitude'),
          'description' => E::ts('Longitude'),
          'where' => 'civicrm_geocodestats.geo_code_2',
          'table_name' => 'civicrm_geocodestats',
          'entity' => 'Geocodestats',
          'bao' => 'CRM_Geocodestats_DAO_Geocodestats',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => '5.27',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'geocodestats', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'geocodestats', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_created_date' => [
        'name' => 'index_created_date',
        'field' => [
          0 => 'created_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_geocodestats::0::created_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
